01/10/2024 11:44:35 AM - ERROR - __main__ - 'Personagem' object has no attribute 'setNome'
Traceback (most recent call last):
  File "c:\Users\kevin\VSProjetos\AutoProducao\main.py", line 2165, in teste
    self.modificaPersonagem()
  File "c:\Users\kevin\VSProjetos\AutoProducao\main.py", line 1970, in modificaPersonagem
    personagem.setNome(novoNome)
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'Personagem' object has no attribute 'setNome'. Did you mean: 'pegaNome'?
02/10/2024 12:32:03 AM - ERROR - personagemDao - table personagens has no column named autoProducao
02/10/2024 12:52:43 AM - ERROR - __main__ - unsupported operand type(s) for +: 'int' and 'UUID'
Traceback (most recent call last):
  File "c:\Users\kevin\VSProjetos\AutoProducao\main.py", line 2238, in teste
    self.modificaProfissao()
  File "c:\Users\kevin\VSProjetos\AutoProducao\main.py", line 1828, in modificaProfissao
    ProfissaoDaoSqlite(personagens[int(opcaoPersonagem) - 1]).insereListaProfissoes()
  File "c:\Users\kevin\VSProjetos\AutoProducao\dao\profissaoDaoSqlite.py", line 57, in insereListaProfissoes
    if self.insereProfissao(Profissao(str(profissoes.index(profissao) + uuid4()), profissao, 0, False)):
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
TypeError: unsupported operand type(s) for +: 'int' and 'UUID'
02/10/2024 12:53:41 AM - ERROR - __main__ - can only concatenate str (not "UUID") to str
Traceback (most recent call last):
  File "c:\Users\kevin\VSProjetos\AutoProducao\main.py", line 2238, in teste
    self.modificaProfissao()
  File "c:\Users\kevin\VSProjetos\AutoProducao\main.py", line 1828, in modificaProfissao
    ProfissaoDaoSqlite(personagens[int(opcaoPersonagem) - 1]).insereListaProfissoes()
  File "c:\Users\kevin\VSProjetos\AutoProducao\dao\profissaoDaoSqlite.py", line 57, in insereListaProfissoes
    if self.insereProfissao(Profissao(str(profissoes.index(profissao)) + uuid4(), profissao, 0, False)):
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
TypeError: can only concatenate str (not "UUID") to str
02/10/2024 10:19:16 AM - ERROR - __main__ - '<' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "c:\Users\kevin\VSProjetos\AutoProducao\main.py", line 2367, in teste
    self.modificaTrabalhoEstoque()
  File "c:\Users\kevin\VSProjetos\AutoProducao\main.py", line 2291, in modificaTrabalhoEstoque
    trabalho.setQuantidade(quantidadeTrabalho)
  File "c:\Users\kevin\VSProjetos\AutoProducao\modelos\trabalhoEstoque.py", line 36, in setQuantidade
    if quantidade < 0:
       ^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'str' and 'int'
02/10/2024 10:20:24 AM - ERROR - estoqueDao - Erro ao inserir trabalho no estoque: 'TrabalhoEstoque' object has no attribute 'pegaRarirdade'
02/10/2024 10:44:57 AM - ERROR - __main__ - Aplicacao.pegaTodosTrabalhosVendidos() takes 0 positional arguments but 1 was given
Traceback (most recent call last):
  File "c:\Users\kevin\VSProjetos\AutoProducao\main.py", line 2426, in teste
    self.pegaTodosTrabalhosVendidos()
TypeError: Aplicacao.pegaTodosTrabalhosVendidos() takes 0 positional arguments but 1 was given
02/10/2024 10:46:37 AM - ERROR - __main__ - TrabalhoVendido.__init__() missing 7 required positional arguments: 'id', 'nomeProduto', 'dataVenda', 'nomePersonagem', 'quantidadeProduto', 'trabalhoId', and 'valorProduto'
Traceback (most recent call last):
  File "c:\Users\kevin\VSProjetos\AutoProducao\main.py", line 2426, in teste
    self.pegaTodosTrabalhosVendidos()
  File "c:\Users\kevin\VSProjetos\AutoProducao\main.py", line 2338, in pegaTodosTrabalhosVendidos
    for trabalhoVendido in TrabalhoVendido().pegaTodosTrabalhosVendidos():
                           ^^^^^^^^^^^^^^^^^
TypeError: TrabalhoVendido.__init__() missing 7 required positional arguments: 'id', 'nomeProduto', 'dataVenda', 'nomePersonagem', 'quantidadeProduto', 'trabalhoId', and 'valorProduto'
02/10/2024 11:28:22 AM - ERROR - estoqueDao - Erro ao inserir trabalho no estoque: UNIQUE constraint failed: Lista_estoque.id
02/10/2024 11:28:34 AM - ERROR - estoqueDao - Erro ao inserir trabalho no estoque: UNIQUE constraint failed: Lista_estoque.id
02/10/2024 11:37:02 AM - ERROR - vendaDao - Erro ao inserir nova venda: 'TrabalhoVendido' object has no attribute 'pegaNomeProduto'
02/10/2024 01:35:44 PM - ERROR - __main__ - invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "c:\Users\kevin\VSProjetos\AutoProducao\main.py", line 2380, in teste
    self.modificaPersonagem()
  File "c:\Users\kevin\VSProjetos\AutoProducao\main.py", line 2044, in modificaPersonagem
    if int(opcaoPersonagem) == 0:
       ^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
02/10/2024 02:07:28 PM - ERROR - estoqueDao - Erro ao inserir trabalho no estoque: UNIQUE constraint failed: Lista_estoque.id
02/10/2024 02:07:42 PM - ERROR - estoqueDao - Erro ao inserir trabalho no estoque: UNIQUE constraint failed: Lista_estoque.id
03/10/2024 12:04:17 AM - ERROR - estoqueDao - Erro ao inserir trabalho no estoque: UNIQUE constraint failed: Lista_estoque.id
